export const courses = [{
  aboutThisCourse: "Professional Scrum Master training prepares you for Scrum Master Levels 1-3 certification.",
  certifyingBody: "Scrum.org",
  cost: "$1000",
  effortDuration: "2 days",
  id: 1,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "Great course; I learned everything I needed and more! I am excited to implement these skills into my role in my organization.",
    "Fantastic experience! Highly recommended! I am looking forward to sharing what I’ve learned with my enterprise.",
    "Raj is an excellent instructor, always willing to help and great at explaining concepts.",
    "This course equipped me with the skills I needed to grow and advance in my career. Many thanks!",
  ],
  role: "Scrum Master",
  title: "Professional Scrum Master Training",
  type: "Scrum.org",
  whatYouLearn: {
    __html: "<p>Apex’s Professional Scrum Master training is your pathway to Scrum Certification!</p><p>Apex’s Professional Scrum Master training courses prepare you for Scrum.org’s Professional Scrum Master levels 1, 2, and 3 examinations.  You will learn from the best: our training is given by industry experts who have decades of experience applying Agile Scrum at leading companies like IBM, edX, PricewaterhouseCoopers, and Boston Consulting Group.   In addition, Apex’s founder, Raj Heda, is currently on the faculty at Boston University and Brandeis University.</p><p>Training Overview</p><ul><li>Scrum Master Level 1 certification requires a thorough understanding of Scrum fundamentals</li><li>Scrum Master Level 2 certification requires an advanced mastery of both Scrum fundamentals and Scrum practice</li><li>Scrum Master Level 3 certification requires a detailed mastery of Scrum practices.</li></ul><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The PSM certification exams are rigorous, but you will be prepared.  Nearly 100% of our graduates pass the exam on their very first attempt.  In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees.  Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your course are available over the Internet 7 days a week and 24 hours a day.  Study at any day and time you want.  Once you are ready, simply sign up to take the certification exam!</p><p><b>Prerequisites:</b> Highly recommended that participants have 5+ years of experience working in software development, business analysis, testing, project management, or product management fields. Experience working in a Scrum environment is also highly desirable.</p>"
  },
},{
  aboutThisCourse: "A Certified ScrumMaster® is able to assist a scrum team to perform at their optimum level, as well as buffering the team from distractions.  The certification process teaches the Scrum framework and enables CSMs to expand their career opportunities using Agile practices.",
  certifyingBody: "Scrum Alliance",
  cost: "$1000",
  effortDuration: "2 days",
  id: 2,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "This class gave me the exposure to agile and the scrum process that I needed. Thanks!",
    "I started with very little knowledge about how agile actually works, but the class provided more than enough to start implementing the techniques at my company.",
    "When I began my training I thought that a scrum master was just a project manager.  The class showed me how the roles are different and how to get a team to work toward a common goal.",
    "My instructor was great. They kept the energy level high, and everyone in the class passed the CSM certification on their first try.  Highly recommended.",
  ],
  role: "Scrum Master",
  title: "CSM – Certified ScrumMaster",
  type: "Scrum Alliance",
  whatYouLearn: {
    __html: "<p>After successfully completing the course, participants will have an understanding of team roles, events and artifacts.  They will be eligible to take CSM test, and upon passing the test, will be asked to accept the CSM License Agreement and complete their Scrum Alliance profile.</p><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The CSM certification exam is rigorous, but you will be prepared. Nearly 100% of our graduates pass the exam on their very first attempt. In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees. Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your course are available over the Internet 7 days a week and 24 hours a day. Study at any day and time you want. Once you are ready, simply sign up to take the certification exam!</p><p><b>Prerequisites:</b> Highly recommended that participants have 5+ years of experience working in software development, business analysis, testing, project management, or product management fields. Experience working in a Scrum environment is also highly desirable.</p>",
  },
},{
  aboutThisCourse: "An advanced course for experienced product owners to prepare for the Scrum Product Owner certificate.",
  certifyingBody: "Scrum Alliance",
  cost: "$1000",
  effortDuration: "2 days",
  id: 3,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "I got a lot from this class.  I’m now able to better manage my team’s backlog, and our outcomes have really improved.",
    "I started with very little knowledge about how agile actually works, but the class provided more than enough to start implementing the techniques at my company.",
    "The class showed me how the product manager role guides a team to work toward a common goal.",
    "My instructor was great. He kept the energy level high and made it easy to learn the material.  Highly recommended.",
  ],
  role: "Product Ownder",
  title: "CSPO – Certified Scrum Product Owner",
  type: "Scrum Alliance",
  whatYouLearn: {
    __html: "<p>A Scrum Product Owner generally comes from the business side of the organization.  In the agile world, the product owner not only manages the vision and backlog, they also help focus the team on providing the outcomes that will delight the customers.</p><p>After successfully completing the course, product owners will have experience as the conduit between the business and the rest of the scrum team.  They’ll learn the skill set that will help them direct the backlog and impart their vision to the team. They will be asked to accept the CSPO License Agreement and complete their Scrum Alliance profile.</p><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The CSPO certification exam is rigorous, but you will be prepared. Nearly 100% of our graduates pass the exam on their very first attempt. In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees. Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your course are available over the Internet 7 days a week and 24 hours a day. Study at any day and time you want. Once you are ready, simply sign up to take the certification exam!</p><p><b>Prerequisites:</b> Highly recommended that participants have 5+ years of experience working in software development, business analysis, testing, project management, or product management fields. Experience working in a Scrum environment is also highly desirable.</p>",
  },
},{
  aboutThisCourse: "A foundational course for developers to prepare for the Scrum Developer scrumalliance.org certificate",
  certifyingBody: "Scrum Alliance",
  cost: "$3000",
  effortDuration: "5 days",
  id: 4,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "This class gave me the exposure to agile and the scrum process that I needed. Thanks!",
    "I started with very little knowledge about how agile actually works, but the class provided more than enough to start implementing the techniques at my company.",
    "Developing in an Agile environment is different than I had expected.  The class showed me the iterative approach and the tools used to deliver good code.",
    "My instructor was great. Five days of training seemed like it would be tough, but the time was well spent.  Highly recommended.",
  ],
  role: "Developer",
  title: "CSD – Certified Scrum Developer",
  type: "Scrum Alliance",
  whatYouLearn: {
    __html: "<p>Designed for developers, this course will hone your agile skills.  Through both formal training and an assessment of your technical skills, you’ll obtain a working knowledge of Scrum and Agile principles.  In addition, you’ll learn the engineering skills used by Agile developers.  The course instructs developers in the tools and techniques for delivering code in an iterative process, key to Agile software development</p><p>Upon completing this course, you will have mastered the skill set required to engage in an Agile development environment.  You’ll become proficient with the tools and techniques used to contribute to an agile team.  Certification as a Certified Scrum Developer demonstrates your commitment to the Agile principles.</p><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The Certified Scrum Developer (CSD) certification exam is rigorous, but you will be prepared. Nearly 100% of our graduates pass the exam on their very first attempt. In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees. Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your course are available over the Internet 7 days a week and 24 hours a day. Study at any day and time you want. Once you are ready, simply sign up to take the certification exam!</p><p><b>Prerequisites:</b> Previous experience as a software developer in an IT organization highly desired, whether from actual industry experience or theory.</p>",
  },
},{
  aboutThisCourse: "A foundational course for the Certified SAFe® Product Owner / Product Manager certificate",
  certifyingBody: "Scaled Agile",
  cost: "$1000",
  effortDuration: "2 days",
  id: 5,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "Great course; I learned everything I needed and more! I am excited to implement these skills into my role in my organization.",
    "Fantastic experience! Highly recommended! I am looking forward to sharing what I’ve learned with my enterprise.",
    "Raj is an excellent instructor, always willing to help and great at explaining concepts.",
    "This course equipped me with the skills I needed to grow and advance in my career. Many thanks!",
  ],
  role: "Product Owner",
  title: "Certified SAFe® Product Owner / Product Manager",
  type: "Scaled Agile",
  whatYouLearn: {
    __html: "<p>If you are seeking to learn how to become a successful Product Owner or Product Manager within a Lean enterprise, this course is designed for you. In this two day course, you will learn the skills necessary to be able to lead a team to deliver high value as you seek to deliver successful products in your organization.</p><p>Trainers will equip you with the knowledge and understanding you need in order to be an effective Product Owner/Product Manager within the Agile Release Train (ART). You will discover how you can utilize Lean thinking within the Agile process as you break down Epics first into Features, and then into Stories. In addition, you will learn about the refinement process and how to best refine and manage features, stories, and product backlogs within Iterations and any Program Increments set forth by your enterprise. Finally, you will learn about Continuous Delivery and DevOps, and how these two entities add to the ongoing improvement that takes place within the Agile Release Train (ART).</p><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The Certified SAFe® Product Owner / Product Manager certification exam is rigorous, but you will be prepared. Nearly 100% of our graduates pass the exam on their very first attempt. In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees. Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your courses are available over the Internet 7 days a week and 24 hours a day. Study at any day and time you want. Once you are ready, simply sign up to take the certification exam!</p><p><b>Prerequisites:</b> Highly recommended that participants attend a course on Leading SAFe®, have work experience in SAFe environment, and have experience in Lean, Agile, or other similar certifications.</p>",
  },
},{
  aboutThisCourse: "An advanced course for experienced developers to prepare for the SAFe Architect certificate.",
  certifyingBody: "Scaled Agile",
  cost: "$1500",
  effortDuration: "3 days",
  id: 6,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "I’ve been a system architect for years – this class enabled me to integrate my experience with the principles of Agile/Lean. Thanks!",
    "I started with very little knowledge about how agile actually works, but the class provided more than enough to start implementing the techniques in my architecture.",
    "Wow – three days was like drinking from a fire hose, and at the end we could understand how to align architecture with business value.",
    "My instructor was great. They kept the energy level high, and we were all engaged.  A must for any architect looking to employ Agile principles.",
  ],
  role: "Architect",
  title: "SAFe® for Architects",
  type: "Scaled Agile",
  whatYouLearn: {
    __html: "<p>Architects in an Agile environment need to understand how to engage their entire organization to improve value flow.  Senior System, Solution and Enterprise Architects will learn how to architect in a way that enables DevOps and Release on Demand.  They’ll understand how to incorporate vision, intent and roadmaps in their designs, and will obtain a deeper appreciation for how architects contribute to an Agile/Lean organization.</p><p>The SAFe for Architects course will give senior technical contributors the skills and understanding to align their designs with the business value, and to steer toward the continuous system-of-systems flow.  Completion of the course allows the participant to take the Certified SAFe® Architect exam.</p><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The SAFe Architect certification exam is rigorous, but you will be prepared. Nearly 100% of our graduates pass the exam on their very first attempt. In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees. Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your course are available over the Internet 7 days a week and 24 hours a day. Study at any day and time you want. Once you are ready, simply sign up to take the certification exam!</p><p><b>Prerequisites:</b> Previous experience as a developer in an IT organization highly desired, whether from actual industry experience or theory.</p>",
  },
},{
  aboutThisCourse: "An intermediate-level course for SAFe practitioners in a Lean-Agile environment.",
  certifyingBody: "Scaled Agile",
  cost: "$1000",
  effortDuration: "2 days",
  id: 7,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "Great course; I learned everything I needed and more! I am excited to implement these skills into my role in my organization.",
    "Fantastic experience! Highly recommended! I am looking forward to sharing what I’ve learned with my enterprise.",
    "Raj is an excellent instructor, always willing to help and great at explaining concepts.",
    "This course equipped me with the skills I needed to grow and advance in my career. Many thanks!",
  ],
  role: "Scrum Master",
  title: "Certified SAFe Practitioner",
  type: "Scaled Agile",
  whatYouLearn: {
    __html: "<p>This two-day course provides attendees with intermediate-level information about using the Scaled Agile Framework® (SAFe®) as a team member Lean-Agile enterprise.  We first review the key concepts behind iterative software development in a SAFe environment, which include managing product backlogs from user stories and requirements, demonstrating value, and incremental and iterative delivery.  We then cover the daily responsibilities of an Agile practitioner and their use of Scrum, Kanban, and Extreme Programming.</p><p>A Certified SAFe Practitioner certificate holder will be expected to show competency in all aspects of an Agile iterative software development environment.  From the perspective of an SAFe practitioner, the course prepares the student in all aspects of the Agile software development process.  Instructors use real-life examples to show students key SAFe skills and then students are given an opportunity to practice the same skills.  As in other SAFe certificate programs, participants in the class explore the importance of adopting a customer-centric mindset and design thinking approach to agile product delivery.</p><h4>Learning Outcome</h4><p>After completing the course, participants will be able to demonstrate their knowledge of the theory and practice needed for participating as a SAFe practitioner in their enterprise.  All students who successfully complete the course will be prepared to take the Certified SAFe® Practitioner (SP) exam.</p><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The Certified SAFe® Practitioner certification exam is rigorous, but you will be prepared. Nearly 100% of our graduates pass the exam on their very first attempt. In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees. Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your course are available over the Internet 7 days a week and 24 hours a day. Study at any day and time you want. Once you are ready, simply sign up to take the certification exam!</p><p><b>Prerequisites:</b> Some experience with Agile software development principles and practices will be helpful, whether from actual industry experience or reading.</p>",
  },
},{
  aboutThisCourse: "A foundational course for the Certified SAFe® Agilist certificate",
  certifyingBody: "Scaled Agile",
  cost: "$1000",
  effortDuration: "2 days",
  id: 8,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "Great course; I learned everything I needed and more! I am excited to implement these skills into my role in my organization.",
    "Fantastic experience! Highly recommended! I am looking forward to sharing what I’ve learned with my enterprise.",
    "Raj is an excellent instructor, always willing to help and great at explaining concepts.",
    "This course equipped me with the skills I needed to grow and advance in my career. Many thanks!",
  ],
  role: "Scrum Master",
  title: "Certified SAFe® Agilist",
  type: "Scaled Agile",
  whatYouLearn: {
    __html: "<p>The goal of this two-day course is to equip you with the knowledge that is needed in order to be at the forefront of a Lean-Agile enterprise. Leading a Lean-Agile enterprise is a demanding task, and this course will provide you with a deep understanding of the Scaled Agile Framework® (SAFe®), so that you can take that framework and apply it to an enterprise.</p><h4>Training Overview</h4><p>During the course, attendees will learn about how to become masters of business agility so that they can use that expertise to rise to the top in the market. Discussions will be centered around how to develop agility within teams and in the technical space, and how to use that agility to reorient how value flows in the organization. Additional discussions and sessions will provide attendees with training on how to embrace a mindset centered around the customer, as well as how to implement design thinking, as they deliver products within an agile methodology. Attendees will also be instructed on how to orchestrate and use PI Planning events, as well as how to manage and direct different Agile Release Trains (ARTs) that run concurrently. Finally, attendees will learn how to execute a Lean Portfolio Management function within their enterprises.</p><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The Certified SAFe® Agilist certification exam is rigorous, but you will be prepared. Nearly 100% of our graduates pass the exam on their very first attempt. In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees. Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your courses are available over the Internet 7 days a week and 24 hours a day. Study at any day and time you want. Once you are ready, simply sign up to take the certification exam!</p><p><b>Prerequisites:</b> Highly recommended that participants have 5+ years of experience working in software development, business analysis, testing, project management, or product management fields. Experience working in a Scrum environment is also highly desirable.</p>",
  },
},{
  aboutThisCourse: "A foundational course for the Certified SAFe® Scrum Master certificate",
  certifyingBody: "Scaled Agile",
  cost: "$1000",
  effortDuration: "2 days",
  id: 9,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "Great course; I learned everything I needed and more! I am excited to implement these skills into my role in my organization.",
    "Fantastic experience! Highly recommended! I am looking forward to sharing what I’ve learned with my enterprise.",
    "Raj is an excellent instructor, always willing to help and great at explaining concepts.",
    "This course equipped me with the skills I needed to grow and advance in my career. Many thanks!",
  ],
  role: "Scrum Master",
  title: "Certified SAFe® Scrum Master",
  type: "Scaled Agile",
  whatYouLearn: {
    __html: "<p>During this course, you will learn about the Scrum Master role within an enterprise operating in the SAFe environment. This course will delve into the specifics of what a Scrum Master role looks like at an enterprise level, not just in the context of a Scrum team. You will step away from this course enabled to plan and implement the Program Increment (PI), which is essential to align every level of an organization operating in a SAFe environment. Because this course is focused on how a Scrum Master fits into an organization at an enterprise level, you will learn how to apply Scrum in every part of your organization, as well as how to use iterative planning in your organization.</p><p>In addition to learning about the role of Scrum Master at an enterprise level, you will also discover how acting as a coach and using servant leadership methods will enable you to create successful Agile teams. Trainers will also demonstrate how the formation of these Agile teams can help your organization reach goals and thrive as they seek to met business goals.</p><p>When you complete this course and gain the Certified SAFe® Scrum Master certificate, this certification will demonstrate to companies that you are equipped and ready to lead Agile teams in a SAFe environment, and that your servant leadership and coaching skills will bring tremendous growth and value to their organizations.</p><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The Certified SAFe® Scrum Master certification exams are rigorous, but you will be prepared. Nearly 100% of our graduates pass the exam on their very first attempt. In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees. Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your course are available over the Internet 7 days a week and 24 hours a day. Study at any day and time you want. Once you are ready, simply sign up to take the certification exam!</p><p><b>Prerequisites:</b> Highly recommended that participants have 5+ years of experience working in software development, business analysis, testing, project management, or product management fields. Experience working in a Scrum environment is also highly desirable.</p>",
  },
},{
  aboutThisCourse: "A foundational course for the Certified SAFe® Government Practitioner certificate",
  certifyingBody: "Scaled Agile",
  cost: "$1000",
  effortDuration: "2 days",
  id: 10,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "Great course; I learned everything I needed and more! I am excited to implement these skills into my role in my organization.",
    "Fantastic experience! Highly recommended! I am looking forward to sharing what I’ve learned with my enterprise.",
    "Raj is an excellent instructor, always willing to help and great at explaining concepts.",
    "This course equipped me with the skills I needed to grow and advance in my career. Many thanks!",
  ],
  role: "Scrum Master",
  title: "Certified SAFe® Government Practitioner",
  type: "Live",
  whatYouLearn: {
    __html: "<p>This course is designed to enable you to be prepared and ready to be at the forefront of a Lean-Agile transformation initiative within a program operating in an agency run by the government. Attendees will learn how to utilize the Scaled Agile Framework® in their government agency in order to provide maximum value through the Lean-Agile transformation.</p><p>During this course you will learn how and why Lean-Agile is a mindset, and the reasons it is essential to bring this mindset as a foundation in a government agency before beginning the transformation. Additionally, you will learn about Agile Release Trains (ART) and how to best utilize them once transformation begins. You will also learn about tailor-made leadership skills and strategies that are best suited to delivering successful transformation and change in the government sector. Trainers will provide best practices and advice on how to best create successful Agile teams, programs, and how to best manage the technology investments that take place in government agencies within the Lean mindset and flow. Finally, you will learn about how to contract in an Agile environment, how to launch your program, and how to ensure you are using SAFe to plan in such a way that ensures you will deliver value to your government agency.</p><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The Certified SAFe® Government Practitioner certification exam is rigorous, but you will be prepared. Nearly 100% of our graduates pass the exam on their very first attempt. In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees. Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your courses are available over the Internet 7 days a week and 24 hours a day. Study at any day and time you want. Once you are ready, simply sign up to take the certification exam!</p><p><b>Prerequisites:</b> Highly recommended that participants have foundational and base understanding of Agile Manifesto, SAFe House of Lean, SAFe Principles, and foundational and base understanding of lifecycle of technology programs in government.</p>",
  },
},{
  aboutThisCourse: "A course to prepare for Professional Scrum Product Owner Certification",
  certifyingBody: "Scrum.org",
  cost: "$1000",
  effortDuration: "2 days",
  id: 11,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "Great course; I learned everything I needed and more! I am excited to implement these skills into my role in my organization.",
    "Fantastic experience! Highly recommended! I am looking forward to sharing what I’ve learned with my enterprise.",
    "Raj is an excellent instructor, always willing to help and great at explaining concepts.",
    "This course equipped me with the skills I needed to grow and advance in my career. Many thanks!",
  ],
  role: "Product Owner",
  title: "Professional Scrum Product Owner",
  type: "Scrum.org",
  whatYouLearn: {
    __html: "<p>Apex’s Professional Scrum Product Owner training is your pathway to Scrum Certification!</p><p>Apex’s Professional Scrum Product Owner training prepares you for Scrum.org’s Professional Scrum Product Owner (PSPO) certification examination. You will learn from the best: our training is given by industry experts who have decades of experience applying Agile Scrum at leading companies like IBM, edX, PricewaterhouseCoopers, and Boston Consulting Group. In addition, Apex’s founder, Raj Heda, is currently on the faculty at Boston University and Brandeis University.</p><h4>Training Overview</h4><p>This two-day course is intended for those with a background in the software industry, whether or not you have previous experience as a product owner.  From the product owner’s perspective we examine the key concepts behind iterative software development in an Agile Scrum environment.  Our instructors provide real examples from industry that demonstrate the product owner’s roles and responsibilities.  From creating user stories to managing product backlogs, to  demonstrating value and incremental and iterative delivery, the product owner’s role is clearly explained  Our instructors also cover the daily responsibilities of Agile team members and their use of Scrum, Kanban, and Extreme Programming.</p><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The PSPO certification exam is rigorous, but you will be prepared. Nearly 100% of our graduates pass the exam on their very first attempt. In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees. Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your course are available over the Internet 7 days a week and 24 hours a day. Study at any day and time you want. Once you are ready, simply sign up to take the certification exam!</p><p><b>Prerequisites:</b> Some experience with Agile software development principles and practices will be helpful, whether from actual industry experience or reading.</p>",
  },
},{
  aboutThisCourse: "Preparation for Scrum.org’s certification as a Professional Scrum Developer ",
  certifyingBody: "Scrum.org",
  cost: "$1500",
  effortDuration: "3 days",
  id: 12,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "Great course; I learned everything I needed and more! I am excited to implement these skills into my role in my organization.",
    "Fantastic experience! Highly recommended! I am looking forward to sharing what I’ve learned with my enterprise.",
    "Raj is an excellent instructor, always willing to help and great at explaining concepts.",
    "This course equipped me with the skills I needed to grow and advance in my career. Many thanks!",
  ],
  role: "Developer",
  title: "Professional Scrum Developer",
  type: "Scrum.org",
  whatYouLearn: {
    __html: "<p>Apex’s Professional Scrum Developer training is your pathway to Scrum Certification!</p><p>Apex’s Professional Scrum Developer training course prepares you for Scrum.org’s Professional Scrum Developer examination. You will learn from the best: our training is given by industry experts who have decades of experience applying Agile Scrum at leading companies like IBM, edX, PricewaterhouseCoopers, and Boston Consulting Group. In addition, Apex’s founder, Raj Heda, is currently on the faculty at Boston University and Brandeis University.</p><h4>Training Overview</h4><p>The Professional Scrum Developer training provides an in-depth understanding of the most important Scrum lessons, drawing from classic texts like the Agile Manifesto and the Scrum Guide, by Ken Schwaber and Jeff Sutherland.  The course is hands-on, with activities drawn from real-world situations.  You will be a member of an Agile team, face real-world challenges, and participate in an actual iterative development effort.  All the while, our expert trainers will be there to demonstrate proper technique and to guide you to prepare for the certification exam.</p><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The PSD certification exam is rigorous, but you will be prepared. Nearly 100% of our graduates pass the exam on their very first attempt. In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees. Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your course are available over the Internet 7 days a week and 24 hours a day. Study at any day and time you want. Once you are ready, simply sign up to take the certification exam!</p><p><b>Prerequisites:</b> Highly recommended that participants have 5+ years of experience working in software development, business analysis, testing, project management, or product management fields. Experience working in a Scrum environment is also highly desirable.</p>",
  },
},{
  aboutThisCourse: "A foundational course for the Project Manager Professional certificate",
  certifyingBody: "Project Management Institute",
  cost: "$2000",
  effortDuration: "4 days",
  id: 13,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "Great course; I learned everything I needed and more! I am excited to implement these skills into my role in my organization.",
    "Fantastic experience! Highly recommended! I am looking forward to sharing what I’ve learned with my enterprise.",
    "Raj is an excellent instructor, always willing to help and great at explaining concepts.",
    "This course equipped me with the skills I needed to grow and advance in my career. Many thanks!",
  ],
  role: "Project Manager",
  title: "Project Management Professional",
  type: "Project Management Institute",
  whatYouLearn: {
    __html: "<p>In this exciting course, you will explore the many aspects and parts that impact the successful management of projects. You will learn about project, program, and portfolio management, and the best practices that accompany each.</p><p>During this course you will dive deep into the PMBOK, where you will learn about the project life cycle. In addition, you will learn about the five process groups lying within the project lifecycle: Initiating, Planning, Executing, Monitoring and Controlling, and Closing. You will then delve into the 10 Knowledge Areas that make up every project: Integration, Scope, Schedule, Cost, Quality, Resource, Communications, Risk, Procurement, and Stakeholder Management. Your trainers will help you understand the inputs, tools and techniques, and outputs within each knowledge area.</p><p>At the end of the course, your trainers will provide you specific instructions and tips on what to do before taking the PMP exam that will guarantee you pass on the first attempt.</p><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The PMP certification exam is rigorous, but you will be prepared. Nearly 100% of our graduates pass the exam on their very first attempt. In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees. Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your courses are available over the Internet 7 days a week and 24 hours a day. Study at any day and time you want. Once you are ready, simply sign up to take the certification exam!</p>",
  },
},{
  aboutThisCourse: "A foundational course for the PMI-ACP certificate",
  certifyingBody: "Project Management Institute",
  cost: "$1000",
  effortDuration: "2 days",
  id: 14,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "Great course; I learned everything I needed and more! I am excited to implement these skills into my role in my organization.",
    "Fantastic experience! Highly recommended! I am looking forward to sharing what I’ve learned with my enterprise.",
    "Raj is an excellent instructor, always willing to help and great at explaining concepts.",
    "This course equipped me with the skills I needed to grow and advance in my career. Many thanks!",
  ],
  role: "Project Manager",
  title: "PMI-ACP",
  type: "Project Management Institute",
  whatYouLearn: {
    __html: "<p>In this two day course, you will learn about the best practices and principles of Agile. The Agile way of working is taking multiple industries by storm, and being equipped with a proper understanding of the various Agile methodologies is key to being successful in the current market.</p><p>This course will provide you an in-depth look at some of the most popular Agile methodologies, like Scrum, Kanban, extreme programming (XP), test-driven development (TDD) and Lean. Throughout the two days of this training course, you will delve deep into these methodologies, and learn the ins and outs of each. You will be prepared to take the PMI-ACP certification test and gain the PMI-ACP certification, which will demonstrate to your colleagues, bosses, and stakeholders involved in your projects that you have a strong understanding of agile. Possessing the PMI-ACP certification will show that you are able to implement agile principles into the workplace in order to bring your organization and team to market success.</p><p>While anyone can apply for this course or certification, it is geared towards those professionals who have experience working in an agile environment, or those whose team, organization, or enterprise is looking to adopt agile practices. If this describes you, sign up for our course today and prepare yourself to take and pass the PMI-ACP certificate.</p><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The PMI-ACP certification exam is rigorous, but you will be prepared. Nearly 100% of our graduates pass the exam on their very first attempt. In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees. Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your courses are available over the Internet 7 days a week and 24 hours a day. Study at any day and time you want. Once you are ready, simply sign up to take the certification exam!</p>",
  },
},{
  aboutThisCourse: "A foundational course for managers to prepare for the Agile Leadership 1 certificate",
  certifyingBody: "Scrum Alliance",
  cost: "$1000",
  effortDuration: "2 days",
  id: 15,
  meetTheInstructors: {
    instructorName: "Raj Heda",
    instructorBio: "Raj Heda has been teaching software development and Agile courses for over 20 years. He has extensive experience leading teams in Agile transformation, with successful results. Raj currently teaches in the Boston area at Boston University and Brandeis University.",
  },
  reviews: [
    "Great course; I learned everything I needed and more! I am excited to implement these skills into my role in my organization.",
    "Fantastic experience! Highly recommended! I am looking forward to sharing what I’ve learned with my enterprise.",
    "Raj is an excellent instructor, always willing to help and great at explaining concepts.",
    "This course equipped me with the skills I needed to grow and advance in my career. Many thanks!",
  ],
  role: "Project Manager",
  title: "Certified Agile Leadership",
  type: "leadership",
  whatYouLearn: {
    __html: "<p>This foundational two-day course provides attendees the background required to achieve the Certified Agile Leadership 1 certification from the Scrum Alliance. The training is oriented towards information technology (IT) product managers, supervisors, directors, leaders, coaches, or anyone in a managerial position who is interested in learning to apply Agile principles to their leadership.</p><p>The applicability of Agile management techniques extends throughout the IT industry and beyond.  This course will demonstrate many of those techniques that prove useful for common organizational and management challenges, such as, effective leadership of distributed and diverse teams, delivering value, and promoting the Scrum values of courage, focus, commitment, respect and openness.   From their experience in both the Agile and non-Agile worlds, Apex’s instructors will show you how to value: individuals and interactions over processes and tools, working software over comprehensive documentation, customer collaboration over contract negotiation, and responding to change over following a plan.</p><p>A Certified Agile Leadership 1 certificate holder will be expected to have an understanding of management practices, particularly those found in IT organizations.  From the perspective of an experienced IT manager, the course prepares the student to apply Agile techniques to attain advanced leadership and management responsibilities in a enterprise  environment. Course instructors draw from their own real-life experience to immerse the student in actual business scenarios.  From there, instructors provide guidance in the application of Agile techniques.</p><p>After completing the course, participants will be able to demonstrate their knowledge of the theory and practice needed for Agile leadership.  All students who successfully complete the course will be prepared to take the Certified Agile Leadership 1 exam.</p><p>Unlike any other training program, we offer the following bonuses:</p><ul><li>The highest passing rates: The Certified Agile Leadership 1 (CAL1) certification exam is rigorous, but you will be prepared. Nearly 100% of our graduates pass the exam on their very first attempt. In the unlikely event that you would need to retake the exam, a second trial is free and additional examinations are discounted.</li><li>Free follow-up access to your course materials for one year.</li><li>25% discount on future course fees. Save on courses as you sail through the certification process.</li></ul><p>Anytime availability: Your course are available over the Internet 7 days a week and 24 hours a day. Study at any day and time you want. Once you are ready, simply sign up to take the certification exam!</p><p><b>Prerequisites:</b> Previous experience as a manager in an IT organization highly desired, whether from actual industry experience or theory.</p>",
  },
}];
